name: spect testing and packaging

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: install build dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
      - name: build wheel
        run: |
          rm -rf ./dist/ ./build/ ./.eggs/ ./src/*.egg-info/
          python3 ./setup.py bdist_wheel
      - name: install wheel
        run: |
          pip install -U ./dist/*.whl
      - name: Test with pytest
        run: |
          pip install pytest # pytest-mock pytest-sugar pytest-cov hypothesis
          pytest
      - name: publish package to PyPI
        uses: pypa/gh-action-pypi-publish@master
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        with:
          user: __token__
          password: ${{ secrets.github_spect_release }}
          packages_dir: ./dist/

